name: Update CVE list

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-cve-list:
    runs-on: ubuntu-latest
    steps:
      - name: Download allitems.csv
        run: curl -LO https://cve.mitre.org/data/downloads/allitems.csv
      - name: Process CVE IDs
        run: |
          python process_cve_list.py
